export const GET_BILLS="GET_BILLS"
export const ERROR="ERROR"
export const ADD_BILL="ADD_BILL"
export const MSG="MSG"
export const GET_BILL="GET_BILL"
export const DELTE_BILL="DELTE_BILL"
export const EDIT_BILL="EDIT_BILL"